defaults:    
    - default_dataset

name: "bdd100k"
train_path: "${pc_config.dataset_path}bdd100k/train/"
val_path: "${pc_config.dataset_path}bdd100k/val/"
test_path: "${pc_config.dataset_path}bdd100k/test/"
semantics: True
train_max_size: 69863
val_max_size: 10000
test_max_size: 0
image_width: 1280
image_height: 720
image_resize_width: 1280 #640 #   1280
image_resize_height: 720 #384 # 768
classes_names: ['person', 'cyclist', 'car', 'truck', 'bus', 'train', 'motorcycle', 'bicycle', 'traffic light', 'traffic sign']
